name: Show dart complilator errors (or don't)

on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Run dart
        run: dart lab2/tests/test.dart
